services:
  database:
    build:
      dockerfile: ./docker/postgres/Dockerfile
    image: postgres
    environment:
      - POSTGRES_USER=codeflix      
      - POSTGRES_PASSWORD=codeflix
      - POSTGRES_DB=codeflix
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postresql/data
    healthcheck:
      test: ["CMD", "telnet", "localhost", "5432"]
      interval: 5s
      timeout: 60s
      retries: 20

  backend:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: dev
    extra_hosts:
      - host.docker.internal:0.0.0.0
    volumes:
      - ./backend:/var/www/html
    env_file:
      - path: ./backend/.env
        required: false
    tty: true
    healthcheck:
      test: ["CMD", "telnet", "localhost", "9000"]
      interval: 5s
      timeout: 60s
      retries: 20
    depends_on:
      database: 
        condition: service_healthy

  nginx:
    image: nginx:latest    
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      backend:
        condition: service_healthy

volumes:
  database: